version: "3"
services:
  prest-db:
    image: postgres:9.6
    container_name: "postgres-prest"
    environment:
      - POSTGRES_DB=prest
      - POSTGRES_USER=postgres
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432